max_concurrency_by_company:
  gemini: 2
  openai: 2
  anthropic: 1
max_retries: 10
retry_backoff_seconds: 10
render_video_fps: 30 # constant, shouldn't change
max_actions_per_turn: 10 # constant, shouldn't change
duration_seconds: 10 # constant, shouldn't change; you can change it to a smaller value for debug
frames_per_action: 3 # constant, shouldn't change
games:
  full:
    - all # constant, shouldn't change
  selected:
    - assault
